GET http://localhost:8080/category 

###

GET http://localhost:8080/category/id

###

POST http://localhost:8080/category
content-type: application/json

{
    "title": "sample"
}

###

DELETE http://localhost:8080/category/id